version: "2"

run:
  timeout: 3m
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: true
  concurrency: 4

output:
  formats:
    tab:
      print-linter-name: true
      colors: true
  sort-order:
    - file
    - severity
    - linter

linters:
  default: all
  disable:
    - godox
    - tagliatelle

  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: io/ioutil
              desc: The io/ioutil package has been deprecated, see https://go.dev/doc/go1.16#ioutil
          allow:
            - $gostd
            - github.com/eser/ajan
            - github.com/eser/aya.is-services
            - github.com/stretchr/testify
            - github.com/go-faker/faker/v4
            - github.com/golang-jwt/jwt/v5
            - github.com/pressly/goose/v3
            - github.com/lib/pq
            - github.com/sqlc-dev/pqtype
            - github.com/spf13/cobra
            - github.com/go-rod/rod
    revive:
      # enable-all-rules: true
      severity: warning
      rules:
        - name: var-naming
          disabled: true
          arguments: []
        # - name: exported
        #   severity: warning
        # - name: error-return
        #   severity: warning
        # - name: error-naming
        #   severity: warning
        # - name: if-return
        #   severity: warning
        # - name: var-naming
        #   severity: warning
        # - name: var-declaration
        #   severity: warning
        # - name: receiver-naming
        #   severity: warning
        # - name: errorf
        #   severity: warning
        # - name: empty-block
        #   severity: warning
        # - name: unused-parameter
        #   severity: warning
        # - name: unreachable-code
        #   severity: warning
        # - name: redefines-builtin-id
        #   severity: warning
        # - name: superfluous-else
        #   severity: warning
        # - name: unexported-return
        #   severity: warning
        # - name: indent-error-flow
        #   severity: warning
        # - name: blank-imports
        #   severity: warning
        # - name: range
        #   severity: warning
        # - name: time-naming
        #   severity: warning
        # - name: context-as-argument
        #   severity: warning
        # - name: context-keys-type
        #   severity: warning
        # - name: indent-error-flow
        #   severity: warning
  exclusions:
    paths:
      - ops
      - tmp

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines

issues:
  fix: true
